name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  LANG: fr_FR.UTF-8

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        sudo apt-get update
        sudo apt-get install -y locales
        sudo locale-gen fr_FR.UTF-8
        sudo update-locale LANG=fr_FR.UTF-8
        pip install -r ./backend/requirements.txt
    - name: Test with pytest
      run: |
        cd backend
        pytest --cov=app
